(defpackage #:cl-sml-compiler-tests
  (:use #:cl #:fiveam #:cl-sml))

(in-package #:cl-sml-compiler-tests)

(def-suite cl-sml-compiler-suite
  :description "Compiler surface tests for emitted Common Lisp forms")

(in-suite cl-sml-compiler-suite)

(test compile-expression-string-emits-expected-cl
  (is (equal '(funcall (funcall #'cl-sml::sml-+ 1) 2)
             (cl-sml:compile-sml-expression-string "1 + 2"
                                                   :package "SML.COMPILER-TEST"))))

(test compile-record-expression-string-emits-record-constructor
  (is (equal '(cl-sml::make-sml-record
               (list (cons "x" 1)
                     (cons "y" 2)))
             (cl-sml:compile-sml-expression-string "{y = 2, x = 1}"
                                                   :package "SML.COMPILER-TEST"))))

(test compile-declarations-string-emits-local-helper-shape
  (let* ((form (cl-sml:compile-sml-declarations-string
                "local fun helper x = x + 1; in val y = helper 2; end;"
                :package "SML.COMPILER-TEST"))
         (printed (write-to-string form :pretty nil)))
    (is (eq 'progn (car form)))
    (is (search "LET" printed))
    (is (search "HELPER" printed))
    (is (search "DEFPARAMETER" printed))
    (is (search "Y" printed))))

(test compile-file-emits-form-and-package-without-evaluation
  (multiple-value-bind (form package)
      (cl-sml:compile-sml-file #P"testdata/sample-program.sml")
    (let ((printed (write-to-string form :pretty nil)))
      (is (eq 'progn (car form)))
      (is (string= "SML.FILE.TESTDATA.SAMPLE-PROGRAM" (package-name package)))
      (is (search "FILE_RESULT" printed)))))

(test compile-functor-argument-value-bindings-tolerate-whitespace
  (is (equal '(("compare" . "TyName.compare"))
             (cl-sml::functor-argument-value-bindings
              "(type ord_key = TyName.TyName; val  compare = TyName.compare)"))))

(test compile-literal-case-uses-native-common-lisp-case
  (let ((form (cl-sml:compile-sml-expression-string
               "case code of 1 => \"one\" | 2 => \"two\" | _ => \"other\""
               :package "SML.COMPILER-TEST")))
    (is (eq 'case (first form)))
    (is (string= "CODE" (symbol-name (second form))))
    (is (equal '(1) (first (third form))))
    (is (equal '(2) (first (fourth form))))
    (is (eq 'otherwise (first (fifth form))))
    (is (search "INVOKE-SML-CASE-ACTION"
                (write-to-string form :pretty nil)))))

(test compile-large-tuple-case-hoists-branch-actions
  (let* ((source
           (with-output-to-string (stream)
             (write-string "case pair of " stream)
             (loop for i below 12
                   do (format stream "~:[~; | ~](~D, x) => x + ~D"
                              (plusp i) i i))
             (write-string " | _ => 0" stream)))
         (form (cl-sml:compile-sml-expression-string
                source :package "SML.COMPILER-TEST"))
         (printed (write-to-string form :pretty nil :circle t)))
    (is (eq 'progn (first form)))
    (is (search "DEFUN" printed))
    (is (search "SML-CASE-ACTION" printed))
    (is (search "CASE-VALUE" printed))))

(test emit-sml-file-writes-loadable-common-lisp
  (let ((artifact #P"testdata/sample-program.generated.lisp"))
    (unwind-protect
         (multiple-value-bind (output package)
             (cl-sml:emit-sml-file #P"testdata/sample-program.sml" artifact
                                   :package "SML.ARTIFACT-TEST")
           (is (probe-file output))
           (is (string= "SML.ARTIFACT-TEST" (package-name package)))
           (let ((text (uiop:read-file-string output)))
             (is (search "Generated by cl-sml" text))
             (is (search "SML.ARTIFACT-TEST" text)))
           (load output)
           (is (= 120 (cl-sml:sml-value "file_result" package))))
      (when (probe-file artifact)
        (delete-file artifact)))))

(test load-sml-file-can-use-interpreted-debug-path
  (multiple-value-bind (package result)
      (cl-sml:load-sml-file #P"testdata/sample-program.sml"
                            :package "SML.INTERPRETED-LOAD-TEST"
                            :compile nil)
    (declare (ignore result))
    (is (= 120 (cl-sml:sml-value "file_result" package)))))

(test load-sml-file-uses-compiled-artifact-path-by-default
  (multiple-value-bind (package result)
      (cl-sml:load-sml-file #P"testdata/sample-program.sml"
                            :package "SML.COMPILED-LOAD-TEST")
    (is (string= "SML.COMPILED-LOAD-TEST" (package-name package)))
    (is (= 120 (cl-sml:sml-value "file_result" package)))
    (is (not (null result)))))

(test load-sml-file-compiles-hoisted-dispatch-helpers
  (multiple-value-bind (package result)
      (cl-sml:load-sml-file #P"testdata/large-dispatch.sml"
                            :package "SML.COMPILED-DISPATCH-TEST")
    (is (not (null result)))
    (is (= 42 (cl-sml:sml-value "dispatch_result" package)))))

(fiveam:run! 'cl-sml-compiler-suite)
