(in-package #:cl-sml)

(defun read-sml-source (stream)
  (with-output-to-string (out)
    (loop for c = (read-char stream nil :eof)
          until (eql c :eof)
          do (write-char c out))))

(defun sml-file-directory (pathname)
  (make-pathname :directory (pathname-directory (truename pathname))))

(defun sml-declaration-start-line-p (line)
  (some (lambda (keyword)
          (let ((length (length keyword)))
            (and (<= length (length line))
                 (string= keyword line :end2 length)
                 (or (= length (length line))
                     (member (char line length)
                             '(#\Space #\Tab #\; #\= #\: #\()
                             :test #'char=)))))
        '("abstype" "datatype" "end" "exception" "fun" "functor" "in"
          "infix" "infixr" "local" "nonfix" "open" "signature"
          "structure" "type" "val" "withtype")))

(defun sml-type-declaration-start-line-p (line)
  (let ((trimmed (string-left-trim '(#\Space #\Tab) line)))
    (and (<= 4 (length trimmed))
         (string= "type" trimmed :end2 4)
         (or (= 4 (length trimmed))
             (member (char trimmed 4) '(#\Space #\Tab #\()
                     :test #'char=)))))

(defun normalize-sml-type-declaration-continuations (source)
  (with-output-to-string (out)
    (let ((in-type-declaration nil)
          (at-start t))
      (dolist (line (uiop:split-string source :separator '(#\Newline)))
        (let* ((trimmed-left (string-left-trim '(#\Space #\Tab) line))
               (starts-declaration (sml-declaration-start-line-p trimmed-left)))
          (cond
            ((and in-type-declaration
                  (not starts-declaration)
                  (plusp (length trimmed-left)))
             (write-char #\Space out)
             (write-string trimmed-left out))
            (t
             (unless at-start
               (write-char #\Newline out))
             (write-string line out)
             (setf in-type-declaration
                   (sml-type-declaration-start-line-p line)))))
        (setf at-start nil)))))

(defun compile-sml-program-string (sml-text &key package source-name
                                                    (type-checker *sml-type-checker*))
  (let* ((*sml-package* (ensure-sml-package (or package (current-sml-package))))
         (normalized
           (normalize-sml-type-declaration-continuations sml-text))
         (ast (esrap:parse 'sml-program normalized)))
    (type-check-sml-string normalized
                           :checker type-checker
                           :filename source-name)
    (compile-with-hoisted-sml-forms
     (lambda () (compile-program ast))
     :identity sml-text)))

(defun compile-sml-declarations-string (sml-text &key package)
  (compile-sml-program-string sml-text :package package))

(defun compile-sml-expression-string (sml-text &key package)
  (let ((*sml-package* (ensure-sml-package (or package (current-sml-package)))))
    (compile-with-hoisted-sml-forms
     (lambda ()
       (compile-expr (esrap:parse 'sml-expr sml-text)))
     :identity sml-text)))

(defun compile-sml-file (pathname &key package)
  (with-open-file (stream pathname :direction :input)
    (let* ((target-package (ensure-sml-package (or package (pathname->sml-package-name pathname))))
           (form (compile-sml-program-string
                  (read-sml-source stream)
                  :package target-package
                  :source-name (namestring pathname))))
      (values form target-package))))

(defun hoisted-sml-function-definition-p (form)
  (and (consp form)
       (eq (first form) 'defun)
       (symbolp (second form))
       (uiop:string-prefix-p "%CL-SML-CASE-ACTION-"
                             (symbol-name (second form)))))

(defun split-hoisted-sml-forms (form)
  (if (and (consp form) (eq (first form) 'progn))
      (loop with hoisted = nil
            with remaining = (rest form)
            while (and remaining
                       (hoisted-sml-function-definition-p (first remaining)))
            do (push (pop remaining) hoisted)
            finally (return (values (nreverse hoisted)
                                    `(progn ,@remaining))))
      (values nil form)))

(defun write-sml-lisp-artifact (form target-package source-pathname stream)
  (let* ((package-name (package-name target-package))
         (source-directory (sml-file-directory source-pathname))
         (*package* (find-package :cl-user))
         (*print-pretty* t)
         (*print-circle* t))
    (format stream ";;; Generated by cl-sml from ~A.~%" source-pathname)
    (pprint '(in-package #:cl-user) stream)
    (pprint `(eval-when (:compile-toplevel :load-toplevel :execute)
               (cl-sml::ensure-sml-package ,package-name))
            stream)
    (multiple-value-bind (hoisted-forms program-form)
        (split-hoisted-sml-forms form)
      (dolist (hoisted-form hoisted-forms)
        (pprint hoisted-form stream))
      (pprint `(let ((cl-sml::*sml-package*
                       (cl-sml::ensure-sml-package ,package-name))
                     (cl-sml::*sml-current-directory* ,source-directory))
                 ,program-form)
              stream))))

(defun emit-sml-file (pathname output-pathname
                      &key package (if-exists :supersede))
  "Compile PATHNAME and write loadable Common Lisp to OUTPUT-PATHNAME."
  (multiple-value-bind (form target-package)
      (compile-sml-file pathname :package package)
    (with-open-file (stream output-pathname
                            :direction :output
                            :if-exists if-exists
                            :if-does-not-exist :create)
      (write-sml-lisp-artifact form target-package pathname stream))
    (values (truename output-pathname) target-package)))

(defun temporary-sml-artifact-pathname ()
  (merge-pathnames
   (make-pathname :name (string-downcase
                         (symbol-name (gensym "cl-sml-load-")))
                  :type "lisp")
   (uiop:temporary-directory)))

(defun execute-compiled-sml-file (form target-package source-pathname)
  ;; COMPILE-FILE lets JVM-hosted CL implementations split very large generated
  ;; programs across methods instead of hitting a single-method bytecode limit.
  (let ((artifact (temporary-sml-artifact-pathname))
        (compiled-artifact nil))
    (unwind-protect
         (progn
           (with-open-file (stream artifact
                                   :direction :output
                                   :if-exists :error
                                   :if-does-not-exist :create)
             (write-sml-lisp-artifact form target-package source-pathname stream))
           (multiple-value-bind (output warnings-p failure-p)
               (handler-bind ((style-warning #'muffle-warning))
                 (compile-file artifact))
             (declare (ignore warnings-p failure-p))
             ;; Some implementations report optimization/type-inference
             ;; warnings as FAILURE-P while still producing a usable FASL.
             (unless (and output (probe-file output))
               (error "Failed to compile generated Lisp for ~A" source-pathname))
             (setf compiled-artifact output))
           (load compiled-artifact))
      (when (and compiled-artifact (probe-file compiled-artifact))
        (delete-file compiled-artifact))
      (when (probe-file artifact)
        (delete-file artifact)))))

(defun load-sml-file (pathname &key package (compile t))
  (multiple-value-bind (form target-package)
      (compile-sml-file pathname :package package)
    (values target-package
            (if compile
                (execute-compiled-sml-file form target-package pathname)
                (let ((*sml-package* target-package)
                      (*sml-current-directory* (sml-file-directory pathname)))
                  (eval form))))))

(defun read-sml-block (stream char arg)
  (declare (ignore char arg))
  (let ((sml-text
          (with-output-to-string (out)
            (loop for c = (read-char stream nil :eof)
                  when (eql c :eof) do (error "Unterminated SML block")
                  when (char= c #\})
                    do (let ((next (read-char stream nil :eof)))
                         (if (char= next #\#)
                             (return)
                             (progn (write-char c out) (write-char next out))))
                  else do (write-char c out)))))
    (compile-sml-program-string sml-text :package (current-sml-package))))

(defreadtable sml-readtable
  (:merge :standard)
  (:macro-char #\# :dispatch)
  (:dispatch-macro-char #\# #\{ #'read-sml-block))
