(in-package #:cl-sml)

(defun string-prefix-p (prefix string)
  (let ((prefix-length (length prefix)))
    (and (<= prefix-length (length string))
         (string= prefix string :end1 prefix-length :end2 prefix-length))))

(defun sanitize-sml-package-fragment (string)
  (let ((upper (string-upcase string)))
    (with-output-to-string (out)
      (loop for ch across upper
            do (write-char (if (or (alphanumericp ch) (char= ch #\-))
                               ch
                               #\-)
                           out)))))

(defun sml-package-name-p (name)
  (or (string= name "SML-USER")
      (string-prefix-p "SML." name)))

(defun ensure-sml-package (designator)
  (let* ((name (etypecase designator
                 (package (package-name designator))
                 (string (string-upcase designator))
                 (symbol (string-upcase (symbol-name designator)))))
         (existing (find-package name)))
    (or existing
        (make-package name :use '("COMMON-LISP")))))

(defun current-sml-package-name (&optional (package *package*))
  (let ((name (package-name (find-package package))))
    (cond
      ((string= name "COMMON-LISP-USER") "SML-USER")
      ((string= name "CL-USER") "SML-USER")
      ((sml-package-name-p name) name)
      (t (format nil "SML.~A" (sanitize-sml-package-fragment name))))))

(defun current-sml-package (&optional (package *package*))
  (ensure-sml-package (current-sml-package-name package)))

(defun pathname->sml-package-name (pathname)
  (let* ((pn (pathname pathname))
         (directory (pathname-directory pn))
         (segments (append (when (listp directory) (rest directory))
                           (list (or (pathname-name pn) "ANONYMOUS")))))
    (format nil "SML.FILE~{.~A~}"
            (mapcar (lambda (segment)
                      (sanitize-sml-package-fragment (princ-to-string segment)))
                    segments))))

(defparameter *sml-package* (ensure-sml-package "SML-USER"))

(defun sml-symbol (name &optional (package *sml-package*))
  (intern (string-upcase name) (ensure-sml-package package)))

(defun export-sml-symbols (symbols &optional (package *sml-package*))
  (when symbols
    (export symbols (ensure-sml-package package)))
  symbols)

(defun make-sml-adt (tag &optional payload)
  (cons tag payload))

(defun sml-unit ()
  (list :tuple))

(defun make-sml-ref (value)
  (vector :ref value))

(defun ensure-sml-ref (cell)
  (unless (and (vectorp cell)
               (= (length cell) 2)
               (eq (aref cell 0) :ref))
    (error "Expected SML ref cell, got ~S" cell))
  cell)

(defun sml-list-hd (list)
  (if list
      (car list)
      (error "hd called on empty list")))

(defun sml-list-tl (list)
  (if list
      (cdr list)
      (error "tl called on empty list")))

;; --- Curried Standard Library ---
;; SML functions are auto-curried. Lisp's standard functions are not.
;; We must wrap Lisp's binary operators into curried closures.
(defun sml-+ (a) (lambda (b) (+ a b)))
(defun sml-- (a) (lambda (b) (- a b)))
(defun sml-* (a) (lambda (b) (* a b)))
(defun sml-div (a) (lambda (b) (truncate a b)))
(defun sml-mod (a) (lambda (b) (mod a b)))
(defun sml-/ (a) (lambda (b) (/ a b)))

(defun sml-< (a) (lambda (b) (< a b)))
(defun sml-> (a) (lambda (b) (> a b)))
(defun sml->= (a) (lambda (b) (>= a b)))
(defun sml-<= (a) (lambda (b) (<= a b)))
(defun sml-= (a) (lambda (b) (equal a b)))
(defun sml-<> (a) (lambda (b) (not (equal a b))))

(defun sml-^ (a) (lambda (b) (concatenate 'string a b)))
(defun sml-@ (a) (lambda (b) (append a b)))

(defun sml-andalso (a) (lambda (b) (and a b)))
(defun sml-orelse (a) (lambda (b) (or a b)))
(defun sml-not (v) (not v))
(defun sml-abs (v) (abs v))
(defun sml-floor (v) (floor v))
(defun sml-ceil (v) (ceiling v))
(defun sml-round (v) (round v))
(defun sml-trunc (v) (truncate v))
(defun sml-sqrt (v) (sqrt v))
(defun sml-sin (v) (sin v))
(defun sml-cos (v) (cos v))
(defun sml-arctan (v) (atan v))
(defun sml-exp (v) (exp v))
(defun sml-ln (v) (log v))
(defun sml-real (v) (coerce v 'double-float))

(defun sml-cons (a) (lambda (b) (cons a b)))
(defun sml-hd (l) (sml-list-hd l))
(defun sml-tl (l) (sml-list-tl l))
(defun sml-length (l) (length l))
(defun sml-null (l) (null l))
(defun sml-rev (l) (reverse l))
(defun sml-map (f) (lambda (l) (mapcar f l)))
(defun sml-app (f)
  (lambda (l)
    (mapc f l)
    (sml-unit)))
(defun sml-foldl (fn)
  (lambda (init)
    (lambda (list)
      (let ((acc init))
        (dolist (item list acc)
          (setf acc (funcall (funcall fn acc) item)))))))
(defun sml-foldr (fn)
  (lambda (init)
    (lambda (list)
      (let ((acc init))
        (dolist (item (reverse list) acc)
          (setf acc (funcall (funcall fn item) acc)))))))
(defun sml-concat (strings)
  (apply #'concatenate 'string strings))

(defun sml-size (string)
  (length string))

(defun sml-explode (string)
  (coerce string 'list))

(defun sml-implode (chars)
  (coerce chars 'string))

(defun sml-ord (char)
  (char-code char))

(defun sml-chr (code)
  (code-char code))

(defun sml-str (char)
  (string char))

(defun sml-o (f)
  (lambda (g)
    (lambda (x)
      (funcall f (funcall g x)))))

(defun sml-before (a)
  (lambda (b)
    (declare (ignore b))
    a))

(defun sml-ref (value)
  (make-sml-ref value))

(defun sml-deref (cell)
  (aref (ensure-sml-ref cell) 1))

(defun sml-assign (cell)
  (lambda (value)
    (setf (aref (ensure-sml-ref cell) 1) value)
    (sml-unit)))

(defun sml-print (value)
  (princ value)
  (sml-unit))

(defparameter *sml-env*
  '(("+" . #'sml-+)
    ("-" . #'sml--)
    ("*" . #'sml-*)
    ("/" . #'sml-/)
    ("div" . #'sml-div)
    ("mod" . #'sml-mod)
    ("^" . #'sml-^)
    ("@" . #'sml-@)
    ("=" . #'sml-=)
    ("<>" . #'sml-<>)
    (">" . #'sml->)
    ("<" . #'sml-<)
    (">=" . #'sml->=)
    ("<=" . #'sml-<=)
    ("::" . #'sml-cons)
    (":=" . #'sml-assign)
    ("!" . #'sml-deref)
    ("ref" . #'sml-ref)
    ("hd" . #'sml-hd)
    ("tl" . #'sml-tl)
    ("length" . #'sml-length)
    ("null" . #'sml-null)
    ("rev" . #'sml-rev)
    ("map" . #'sml-map)
    ("app" . #'sml-app)
    ("foldl" . #'sml-foldl)
    ("foldr" . #'sml-foldr)
    ("concat" . #'sml-concat)
    ("size" . #'sml-size)
    ("explode" . #'sml-explode)
    ("implode" . #'sml-implode)
    ("ord" . #'sml-ord)
    ("chr" . #'sml-chr)
    ("str" . #'sml-str)
    ("abs" . #'sml-abs)
    ("floor" . #'sml-floor)
    ("ceil" . #'sml-ceil)
    ("round" . #'sml-round)
    ("trunc" . #'sml-trunc)
    ("sqrt" . #'sml-sqrt)
    ("sin" . #'sml-sin)
    ("cos" . #'sml-cos)
    ("arctan" . #'sml-arctan)
    ("exp" . #'sml-exp)
    ("ln" . #'sml-ln)
    ("real" . #'sml-real)
    ("o" . #'sml-o)
    ("before" . #'sml-before)
    ("not" . #'sml-not)
    ("print" . #'sml-print)
    ("Math.pi" . pi)
    ("true" . t)
    ("false" . nil)
    ("nil" . nil)))
