(in-package #:cl-sml)

(defun string-prefix-p (prefix string)
  (let ((prefix-length (length prefix)))
    (and (<= prefix-length (length string))
         (string= prefix string :end1 prefix-length :end2 prefix-length))))

(defun sanitize-sml-package-fragment (string)
  (let ((upper (string-upcase string)))
    (with-output-to-string (out)
      (loop for ch across upper
            do (write-char (if (or (alphanumericp ch) (char= ch #\-))
                               ch
                               #\-)
                           out)))))

(defun sml-package-name-p (name)
  (or (string= name "SML-USER")
      (string-prefix-p "SML." name)))

(defun ensure-sml-package (designator)
  (let* ((name (etypecase designator
                 (package (package-name designator))
                 (string (string-upcase designator))
                 (symbol (string-upcase (symbol-name designator)))))
         (existing (find-package name)))
    (or existing
        (make-package name :use '("COMMON-LISP")))))

(defun current-sml-package-name (&optional (package *package*))
  (let ((name (package-name (find-package package))))
    (cond
      ((string= name "COMMON-LISP-USER") "SML-USER")
      ((string= name "CL-USER") "SML-USER")
      ((sml-package-name-p name) name)
      (t (format nil "SML.~A" (sanitize-sml-package-fragment name))))))

(defun current-sml-package (&optional (package *package*))
  (ensure-sml-package (current-sml-package-name package)))

(defun pathname->sml-package-name (pathname)
  (let* ((pn (pathname pathname))
         (directory (pathname-directory pn))
         (segments (append (when (listp directory) (rest directory))
                           (list (or (pathname-name pn) "ANONYMOUS")))))
    (format nil "SML.FILE~{.~A~}"
            (mapcar (lambda (segment)
                      (sanitize-sml-package-fragment (princ-to-string segment)))
                    segments))))

(defparameter *sml-package* (ensure-sml-package "SML-USER"))

(defparameter *sml-binding-types* (make-hash-table :test #'eq))

(defparameter *sml-exception-function-tags* (make-hash-table :test #'eq))

(defstruct (sml-exception-tag
            (:constructor %make-sml-exception-tag (name)))
  name)

(defun make-sml-exception-constructor (name)
  (%make-sml-exception-tag name))

(defun make-sml-exception-function (name)
  (let* ((tag (make-sml-exception-constructor name))
         (constructor (lambda (payload)
                        (cons tag payload))))
    (setf (gethash constructor *sml-exception-function-tags*) tag)
    constructor))

(defun sml-exception-constructor-tag (constructor)
  (cond
    ((sml-exception-tag-p constructor) constructor)
    ((functionp constructor)
     (or (gethash constructor *sml-exception-function-tags*)
         (error "Unknown SML exception constructor function: ~S" constructor)))
    ((and (consp constructor) (sml-exception-tag-p (car constructor)))
     (car constructor))
    (t
     (error "Not an SML exception constructor or value: ~S" constructor))))

(defun sml-exception-p (value)
  (or (sml-exception-tag-p value)
      (and (consp value)
           (sml-exception-tag-p (car value)))))

(defun sml-exception-payload (value)
  (and (consp value)
       (sml-exception-tag-p (car value))
       (cdr value)))

(defun sml-exception-name (value)
  (sml-exception-tag-name (sml-exception-constructor-tag value)))

(defparameter *sml-builtin-type-env*
  '(("+" . (:fn "int" (:fn "int" "int")))
    ("-" . (:fn "int" (:fn "int" "int")))
    ("*" . (:fn "int" (:fn "int" "int")))
    ("/" . (:fn "real" (:fn "real" "real")))
    ("div" . (:fn "int" (:fn "int" "int")))
    ("mod" . (:fn "int" (:fn "int" "int")))
    ("^" . (:fn "string" (:fn "string" "string")))
    ("@" . (:fn (:list :unknown) (:fn (:list :unknown) (:list :unknown))))
    ("=" . (:fn :unknown (:fn :unknown "bool")))
    ("<>" . (:fn :unknown (:fn :unknown "bool")))
    (">" . (:fn "int" (:fn "int" "bool")))
    ("<" . (:fn "int" (:fn "int" "bool")))
    (">=" . (:fn "int" (:fn "int" "bool")))
    ("<=" . (:fn "int" (:fn "int" "bool")))
    ("::" . (:fn :unknown (:fn (:list :unknown) (:list :unknown))))
    (":=" . (:fn "ref" (:fn :unknown "unit")))
    ("!" . (:fn "ref" :unknown))
    ("ref" . (:fn :unknown "ref"))
    ("hd" . (:fn (:list :unknown) :unknown))
    ("tl" . (:fn (:list :unknown) (:list :unknown)))
    ("length" . (:fn (:list :unknown) "int"))
    ("null" . (:fn (:list :unknown) "bool"))
    ("rev" . (:fn (:list :unknown) (:list :unknown)))
    ("map" . (:fn (:fn :unknown :unknown) (:fn (:list :unknown) (:list :unknown))))
    ("app" . (:fn (:fn :unknown "unit") (:fn (:list :unknown) "unit")))
    ("foldl" . (:fn (:fn :unknown (:fn :unknown :unknown)) (:fn :unknown (:fn (:list :unknown) :unknown))))
    ("foldr" . (:fn (:fn :unknown (:fn :unknown :unknown)) (:fn :unknown (:fn (:list :unknown) :unknown))))
    ("concat" . (:fn (:list "string") "string"))
    ("size" . (:fn "string" "int"))
    ("explode" . (:fn "string" (:list "char")))
    ("implode" . (:fn (:list "char") "string"))
    ("ord" . (:fn "char" "int"))
    ("chr" . (:fn "int" "char"))
    ("str" . (:fn "char" "string"))
    ("abs" . (:fn "int" "int"))
    ("floor" . (:fn "real" "int"))
    ("ceil" . (:fn "real" "int"))
    ("round" . (:fn "real" "int"))
    ("trunc" . (:fn "real" "int"))
    ("sqrt" . (:fn "real" "real"))
    ("sin" . (:fn "real" "real"))
    ("cos" . (:fn "real" "real"))
    ("arctan" . (:fn "real" "real"))
    ("exp" . (:fn "real" "real"))
    ("ln" . (:fn "real" "real"))
    ("real" . (:fn "int" "real"))
    ("o" . (:fn (:fn :unknown :unknown) (:fn (:fn :unknown :unknown) (:fn :unknown :unknown))))
    ("before" . (:fn :unknown (:fn :unknown :unknown)))
    ("not" . (:fn "bool" "bool"))
    ("print" . (:fn :unknown "unit"))
    ("Math.pi" . "real")
    ("true" . "bool")
    ("false" . "bool")
    ("nil" . (:list :unknown))))

(defun sml-symbol (name &optional (package *sml-package*))
  (intern (string-upcase name) (ensure-sml-package package)))

(defun export-sml-symbols (symbols &optional (package *sml-package*))
  (when symbols
    (export symbols (ensure-sml-package package)))
  symbols)

(defun register-sml-binding-type (symbol type)
  (setf (gethash symbol *sml-binding-types*) type))

(defun lookup-sml-binding-type (symbol-or-name &optional (package *sml-package*))
  (etypecase symbol-or-name
    (symbol (gethash symbol-or-name *sml-binding-types*))
    (string (or (cdr (assoc symbol-or-name *sml-builtin-type-env* :test #'string=))
                (let ((symbol (find-symbol (string-upcase symbol-or-name)
                                           (package-name (ensure-sml-package package)))))
                  (and symbol (gethash symbol *sml-binding-types*)))))))

(defun sml-type->cl-type (type)
  (cond
    ((null type) t)
    ((stringp type)
     (cond
       ((string= type "int") 'integer)
       ((string= type "real") 'double-float)
       ((string= type "string") 'string)
       ((string= type "char") 'character)
       ((string= type "bool") 'boolean)
       ((string= type "unit") 'list)
       ((string= type "ref") 'vector)
       ((string= type "exn") t)
       (t t)))
    ((and (consp type) (eq (car type) :list))
     'list)
    ((and (consp type) (eq (car type) :tuple))
     'list)
    ((and (consp type) (eq (car type) :record))
     'list)
    ((and (consp type) (eq (car type) :fn))
     'function)
    (t t)))

(defun unify-sml-types (left right)
  (cond
    ((equal left right) left)
    ((eq left :unknown) right)
    ((eq right :unknown) left)
    (t :unknown)))

(defun infer-sml-list-type (elements &optional (package *sml-package*))
  (let ((element-type :unknown))
    (dolist (element elements (list :list element-type))
      (setf element-type
            (unify-sml-types element-type
                             (infer-sml-ast-type element :package package))))))

(defun infer-sml-record-type (fields &optional (package *sml-package*))
  (cons :record
        (sort-sml-record-fields
         (mapcar (lambda (field)
                   (cons (first field)
                         (infer-sml-ast-type (second field) :package package)))
                 fields))))

(defun infer-sml-ast-type (ast &key (package *sml-package*))
  (cond
    ((integerp ast) "int")
    ((typep ast 'double-float) "real")
    ((stringp ast) "string")
    ((characterp ast) "char")
    ((and (listp ast) (eq (car ast) :unit)) "unit")
    ((and (listp ast) (eq (car ast) :tuple))
     (cons :tuple (mapcar (lambda (item)
                            (infer-sml-ast-type item :package package))
                          (cdr ast))))
    ((and (listp ast) (eq (car ast) :record))
     (infer-sml-record-type (cdr ast) package))
    ((and (listp ast) (eq (car ast) :list))
     (infer-sml-list-type (cdr ast) package))
    ((and (listp ast) (member (car ast) '(:var :ctor) :test #'eq))
     (or (lookup-sml-binding-type (second ast) package) :unknown))
    ((and (listp ast) (eq (car ast) :selector))
     `(:fn (:record ((,(second ast) . :unknown))) :unknown))
    ((and (listp ast) (eq (car ast) :raise))
     :unknown)
    ((and (listp ast) (eq (car ast) :handle))
     (reduce #'unify-sml-types
             (cons (infer-sml-ast-type (second ast) :package package)
                   (mapcar (lambda (branch)
                             (infer-sml-ast-type (second branch) :package package))
                           (third ast)))
             :initial-value :unknown))
    ((and (listp ast) (eq (car ast) :if))
     (unify-sml-types (infer-sml-ast-type (third ast) :package package)
                      (infer-sml-ast-type (fourth ast) :package package)))
    ((and (listp ast) (eq (car ast) :seq))
     (infer-sml-ast-type (car (last ast)) :package package))
    ((and (listp ast) (eq (car ast) :let))
     (infer-sml-ast-type (car (last (third ast))) :package package))
    ((and (listp ast) (eq (car ast) :fn))
     '(:fn :unknown :unknown))
    ((and (listp ast) (eq (car ast) :case))
     (let ((branch-types
             (mapcar (lambda (branch)
                       (infer-sml-ast-type (second branch) :package package))
                     (cddr ast))))
       (reduce #'unify-sml-types branch-types :initial-value :unknown)))
    ((and (listp ast) (eq (car ast) :app))
     (let ((head (second ast))
           (head-type (infer-sml-ast-type (second ast) :package package)))
       (cond
         ((and (listp head) (eq (car head) :selector))
          (let ((arg-type (infer-sml-ast-type (third ast) :package package)))
            (if (and (consp arg-type) (eq (car arg-type) :record))
                (or (cdr (assoc (second head) (cdr arg-type) :test #'string=))
                    :unknown)
                :unknown)))
         ((and (consp head-type) (eq (car head-type) :fn))
          (third head-type))
         (t
          :unknown))))
    ((and (listp ast) (member (car ast) '(:andalso :orelse) :test #'eq))
     "bool")
    (t :unknown)))

(defun sml-type->string (type)
  (cond
    ((null type) "<unknown>")
    ((eq type :unknown) "<unknown>")
    ((stringp type) type)
    ((and (consp type) (eq (car type) :list))
     (format nil "~A list" (sml-type->string (second type))))
    ((and (consp type) (eq (car type) :tuple))
     (format nil "(~{~A~^ * ~})" (mapcar #'sml-type->string (cdr type))))
    ((and (consp type) (eq (car type) :record))
     (format nil "{~{~A~^, ~}}"
             (mapcar (lambda (field)
                       (format nil "~A: ~A"
                               (car field)
                               (sml-type->string (cdr field))))
                     (cdr type))))
    ((and (consp type) (eq (car type) :fn))
     (format nil "~A -> ~A"
             (sml-type->string (second type))
             (sml-type->string (third type))))
    (t (princ-to-string type))))

(defun sort-sml-record-fields (fields)
  (sort (copy-list fields) #'string< :key #'car))

(defun make-sml-record (fields)
  (cons :record (sort-sml-record-fields fields)))

(defun sml-record-p (value)
  (and (consp value)
       (eq (car value) :record)))

(defun sml-record-fields (record)
  (if (sml-record-p record)
      (cdr record)
      (error "Expected SML record, got ~S" record)))

(defun sml-record-select (record label)
  (let ((field (assoc label (sml-record-fields record) :test #'string=)))
    (if field
        (cdr field)
        (error "Record does not contain field ~A: ~S" label record))))

(define-condition sml-raised-exception (error)
  ((value :initarg :value :reader sml-exception-value))
  (:report (lambda (condition stream)
             (format stream "Unhandled SML exception: ~A"
                     (sml-exception-value condition)))))

(defun sml-raise (value)
  (error 'sml-raised-exception :value value))

(defun make-sml-adt (tag &optional payload)
  (cons tag payload))

(defun sml-unit ()
  (list :tuple))

(defun make-sml-ref (value)
  (vector :ref value))

(defun ensure-sml-ref (cell)
  (unless (and (vectorp cell)
               (= (length cell) 2)
               (eq (aref cell 0) :ref))
    (error "Expected SML ref cell, got ~S" cell))
  cell)

(defun sml-list-hd (list)
  (if list
      (car list)
      (error "hd called on empty list")))

(defun sml-list-tl (list)
  (if list
      (cdr list)
      (error "tl called on empty list")))

;; --- Curried Standard Library ---
;; SML functions are auto-curried. Lisp's standard functions are not.
;; We must wrap Lisp's binary operators into curried closures.
(defun sml-+ (a) (lambda (b) (+ a b)))
(defun sml-- (a) (lambda (b) (- a b)))
(defun sml-* (a) (lambda (b) (* a b)))
(defun sml-div (a) (lambda (b) (truncate a b)))
(defun sml-mod (a) (lambda (b) (mod a b)))
(defun sml-/ (a) (lambda (b) (/ a b)))

(defun sml-< (a) (lambda (b) (< a b)))
(defun sml-> (a) (lambda (b) (> a b)))
(defun sml->= (a) (lambda (b) (>= a b)))
(defun sml-<= (a) (lambda (b) (<= a b)))
(defun sml-= (a) (lambda (b) (equal a b)))
(defun sml-<> (a) (lambda (b) (not (equal a b))))

(defun sml-^ (a) (lambda (b) (concatenate 'string a b)))
(defun sml-@ (a) (lambda (b) (append a b)))

(defun sml-andalso (a) (lambda (b) (and a b)))
(defun sml-orelse (a) (lambda (b) (or a b)))
(defun sml-not (v) (not v))
(defun sml-abs (v) (abs v))
(defun sml-floor (v) (floor v))
(defun sml-ceil (v) (ceiling v))
(defun sml-round (v) (round v))
(defun sml-trunc (v) (truncate v))
(defun sml-sqrt (v) (coerce (sqrt v) 'double-float))
(defun sml-sin (v) (coerce (sin v) 'double-float))
(defun sml-cos (v) (coerce (cos v) 'double-float))
(defun sml-arctan (v) (coerce (atan v) 'double-float))
(defun sml-exp (v) (coerce (exp v) 'double-float))
(defun sml-ln (v) (coerce (log v) 'double-float))
(defun sml-real (v) (coerce v 'double-float))

(defun sml-cons (a) (lambda (b) (cons a b)))
(defun sml-hd (l) (sml-list-hd l))
(defun sml-tl (l) (sml-list-tl l))
(defun sml-length (l) (length l))
(defun sml-null (l) (null l))
(defun sml-rev (l) (reverse l))
(defun sml-map (f) (lambda (l) (mapcar f l)))
(defun sml-app (f)
  (lambda (l)
    (mapc f l)
    (sml-unit)))
(defun sml-foldl (fn)
  (lambda (init)
    (lambda (list)
      (let ((acc init))
        (dolist (item list acc)
          (setf acc (funcall (funcall fn acc) item)))))))
(defun sml-foldr (fn)
  (lambda (init)
    (lambda (list)
      (let ((acc init))
        (dolist (item (reverse list) acc)
          (setf acc (funcall (funcall fn item) acc)))))))
(defun sml-concat (strings)
  (apply #'concatenate 'string strings))

(defun sml-size (string)
  (length string))

(defun sml-explode (string)
  (coerce string 'list))

(defun sml-implode (chars)
  (coerce chars 'string))

(defun sml-ord (char)
  (char-code char))

(defun sml-chr (code)
  (code-char code))

(defun sml-str (char)
  (string char))

(defun sml-o (f)
  (lambda (g)
    (lambda (x)
      (funcall f (funcall g x)))))

(defun sml-before (a)
  (lambda (b)
    (declare (ignore b))
    a))

(defun sml-ref (value)
  (make-sml-ref value))

(defun sml-deref (cell)
  (aref (ensure-sml-ref cell) 1))

(defun sml-assign (cell)
  (lambda (value)
    (setf (aref (ensure-sml-ref cell) 1) value)
    (sml-unit)))

(defun sml-print (value)
  (princ value)
  (sml-unit))

(defparameter *sml-env*
  '(("+" . #'sml-+)
    ("-" . #'sml--)
    ("*" . #'sml-*)
    ("/" . #'sml-/)
    ("div" . #'sml-div)
    ("mod" . #'sml-mod)
    ("^" . #'sml-^)
    ("@" . #'sml-@)
    ("=" . #'sml-=)
    ("<>" . #'sml-<>)
    (">" . #'sml->)
    ("<" . #'sml-<)
    (">=" . #'sml->=)
    ("<=" . #'sml-<=)
    ("::" . #'sml-cons)
    (":=" . #'sml-assign)
    ("!" . #'sml-deref)
    ("ref" . #'sml-ref)
    ("hd" . #'sml-hd)
    ("tl" . #'sml-tl)
    ("length" . #'sml-length)
    ("null" . #'sml-null)
    ("rev" . #'sml-rev)
    ("map" . #'sml-map)
    ("app" . #'sml-app)
    ("foldl" . #'sml-foldl)
    ("foldr" . #'sml-foldr)
    ("concat" . #'sml-concat)
    ("size" . #'sml-size)
    ("explode" . #'sml-explode)
    ("implode" . #'sml-implode)
    ("ord" . #'sml-ord)
    ("chr" . #'sml-chr)
    ("str" . #'sml-str)
    ("abs" . #'sml-abs)
    ("floor" . #'sml-floor)
    ("ceil" . #'sml-ceil)
    ("round" . #'sml-round)
    ("trunc" . #'sml-trunc)
    ("sqrt" . #'sml-sqrt)
    ("sin" . #'sml-sin)
    ("cos" . #'sml-cos)
    ("arctan" . #'sml-arctan)
    ("exp" . #'sml-exp)
    ("ln" . #'sml-ln)
    ("real" . #'sml-real)
    ("o" . #'sml-o)
    ("before" . #'sml-before)
    ("not" . #'sml-not)
    ("print" . #'sml-print)
    ("Math.pi" . pi)
    ("true" . t)
    ("false" . nil)
    ("nil" . nil)))
